### PR TITLE
Stop working at Netflix btw

### PR DESCRIPTION
**Pull request by The-Briel-Deal**
You stopped working at Netflix btw

### CODE REVIEW

**Comment by itsmenewbie03** [comment]
this should be merged ASAP

**Comment by iljo-dp-hogent** [comment]
LGTM! should be merged ASAP KEKW

**Comment by ThePrimeagen** [comment]
Merged

**Comment by The-Briel-Deal** [comment]
Let's go team! Great work on the high velocity reviews! 🍾

**Pull request merged**
